- name: "| miniconda | Get zsh path."
  shell: which zsh
  args:
    executable: /bin/bash
  register: zsh
- name: Print out
  debug:
    var: zsh

- name: "| miniconda | Mkdir miniconda3 and Download."
  shell: mkdir -p ./miniconda3 && wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ./miniconda3/miniconda.sh
  args:
    chdir: /home/{{ user }}
    executable: "{{ zsh.stdout }}"
  register: result
- name: Print out
  debug:
    var: result

- name: "| miniconda | Install miniconda3."
  shell: bash ./miniconda3/miniconda.sh -b -u -p ./miniconda3
  args:
    chdir: /home/{{ user }}
    executable: "{{ zsh.stdout }}"
  register: result
- name: Print out
  debug:
    var: result

- name: "| miniconda | Remove download file."
  shell: rm -rf ./miniconda3/miniconda.sh
  args:
    chdir: /home/{{ user }}
    executable: "{{ zsh.stdout }}"
  register: result
- name: Print out
  debug:
    var: result

- name: "| miniconda3 | Init miniconda3 zsh."
  shell: ./miniconda3/bin/conda init zsh
  args:
    chdir: /home/{{ user }}
    executable: "{{ zsh.stdout }}"
  register: result
- name: Print out
  debug:
    var: result

- name: "| miniconda3 | Disable auto_activate_base."
  shell: conda config --set auto_activate_base False
  args:
    executable: "{{ zsh.stdout }}"
  register: result
- name: Print out
  debug:
    var: result

- name: "| miniconda3 | Verify auto_activate_base is False."
  shell: conda config --show | grep auto_activate_base
  args:
    executable: "{{ zsh.stdout }}"
  register: result
- name: Print out
  debug:
    var: result

- name: "| miniconda3 | Turn off changeps1."
  shell: conda config --set changeps1 True
  args:
    executable: "{{ zsh.stdout }}"
  register: result
- name: Print out
  debug:
    var: result

- name: "| miniconda3 | Verify changeps1 is False."
  shell: conda config --show | grep changeps1
  args:
    executable: "{{ zsh.stdout }}"
  register: result
- name: Print out
  debug:
    var: result
