- name: Install require library
  apt:
    pkg:
      - tmux
    update_cache: yes

- name: Get zsh path
  shell: which zsh
  args:
    executable: /bin/bash
  register: zsh

- name: Change network interface
  shell: sed -i "s/<NET-INTERFACE>/$(ip -o link | head -n 2 | tail -n 1 | cut -d ':' -f 2 | cut -d ' ' -f 2)/g" /home/{{ user }}/Dotfile-config/tmux/.tmux.conf
  args:
    chdir: /home/{{ user }}
    executable: "{{ zsh.stdout }}"

- name: Create .config folder
  file:
    path: /home/{{ user }}/.config
    state: directory

- name: Copy .tmux.conf file
  copy:
    src: /home/{{ user }}/Dotfile-config/tmux/.tmux.conf
    dest: /home/{{ user }}/.config/.tmux.conf

- name: Git Clone - Install plugin tmp
  ansible.builtin.git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: "/home/{{ user }}/.tmux/plugins/tpm"

- name: Git Clone - Install plugin tmux-nova
  ansible.builtin.git:
    repo: 'https://github.com/o0th/tmux-nova.git'
    dest: "/home/{{ user }}/.tmux/plugins/tmux-nova"

- name: Git Clone - Install plugin tmux-cpu
  ansible.builtin.git:
    repo: 'https://github.com/tmux-plugins/tmux-cpu.git'
    dest: "/home/{{ user }}/.tmux/plugins/tmux-cpu"

- name: Git Clone - Install plugin tmux-net-speed
  ansible.builtin.git:
    repo: 'https://github.com/tmux-plugins/tmux-net-speed.git'
    dest: "/home/{{ user }}/.tmux/plugins/tmux-net-speed"


