- name: "tmux]-[Get zsh path"
  shell: which zsh
  args:
    executable: /bin/bash
  register: zsh
- name: "----"
  debug:
    msg: "Executable: {{ zsh.stdout }}"

- name: "tmux]-[Install require library"
  shell: pacman -S tmux --noconfirm
  args:
    executable: "{{ zsh.stdout }}"
  register: result

- name: "tmux]-[Link .tmux.conf file"
  shell: ln -sf /home/{{ user }}/Dotfile-config/tmux/.tmux.conf /home/{{ user }}/.tmux.conf
  args:
    chdir: /home/{{ user }}
  register: result

- name: "tmux]-[Verify ~/.tmux folder"
  stat:
    path: /home/{{ user }}/.tmux
  register: result
- name: "starship]-[Create ~/.tmux folder"
  become_user: "{{ user }}"
  file:
    path: /home/{{ user }}/.tmux
    state: directory
  when: not result.stat.exists
  register: result
- name: "----"
  debug:
    msg: "{% if result.changed == true %}Created ~/.tmux folder{% else %}Folder ~/.tmux is exists{% endif %}"

- name: "tmux]-[Git Clone - Install plugin tpm"
  become_user: "{{ user }}"
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "/home/{{ user }}/.tmux/plugins/tpm"
  register: result
- name: "tmux]-[Verify install tpm"
  stat:
    path: /home/{{ user }}/.tmux/plugins/tpm
  register: result
- name: "----"
  debug:
    msg: "{% if result.stat.exists %}Install tpm successful.{% else %}Install tpm not complete.{% endif %}"

- name: "tmux]-[Git Clone - Install plugin tmux-nova"
  become_user: "{{ user }}"
  ansible.builtin.git:
    repo: "https://github.com/o0th/tmux-nova.git"
    dest: "/home/{{ user }}/.tmux/plugins/tmux-nova"
  register: result
- name: "tmux]-[Verify install tmux-nova"
  stat:
    path: /home/{{ user }}/.tmux/plugins/tmux-nova
  register: result
- name: "----"
  debug:
    msg: "{% if result.stat.exists %}Install tmux-nova successful.{% else %}Install tmux-nova not complete.{% endif %}"
